version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/app/deploy/ # 배포 파일 도착 폴더
    overwrite: yes 
    # 이 설정을 해도 덮어써지지 않는 다는 말이 있는데 저는 일단 잘되서 사용중입니다.
    # 제대로 되지않는다면, 아래 hooks BeforeInstall 를 추가하여, 존재하는 파일을 삭제하는 방법이 있습니다
    
permissions:
  - object: /
    pattern: "**" # 모든 파일의 권한 설정
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
#  AfterInstall: # 파일이 도착 후 실행
#    - location: stop.sh # nginx와 연결되지 않은 스프링 부트 종료
#      timeout: 60 # 60 안에 실행, 60 뒤엔 배포 실패로 변경
#      runas: ec2-user
#  ApplicationStart:
#    - location: start.sh # nginx와 연결되어 있지 않은 포트로 스프링 부트 시작.
#      timeout: 60 # 60 안에 실행, 60 뒤엔 배포 실패로 변경
#      runas: ec2-user
#  ValidateService:
#    - location: health.sh # 새 서비스 health check
#      timeout: 60 # 60 안에 실행, 60 뒤엔 배포 실패로 변경
#      runas: ec2-user
