
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-connections: 10000
    threads:
      max: 200
spring:
  application:
    name: "springboot-webservice"
#DB Setting
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://rds-mariadb-1.c71rqnr1tpfo.ap-northeast-2.rds.amazonaws.com:3306/COMMON
    username: admin
    password: qpalzm1!
    sql-script-encoding: UTF-8
